name: CryptoPivots
title: CryptoPivots
markdown: kramdown
kramdown:
  input: GFM
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme

show_downloads: true
google_analytics:

sass:
  sass_dir: assets/css
